{
 "title": "Dashbord Escolar",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "filter_sexo",
    "label": "Sexo",
    "query": "select distinct sexo from relacional.tb_cubo_matriculas"
   },
   {
    "name": "filter_deficiencia",
    "label": "Deficiencia",
    "query": "select distinct deficiencia from relacional.tb_cubo_matriculas where Sexo in ($filter_sexo)"
   },
   {
    "name": "filter_transporte",
    "label": "Transporte",
    "query": "select distinct transporte from relacional.tb_cubo_matriculas where Sexo in ($filter_sexo) and Deficiencia in ($filter_deficiencia)"
   },
   {
    "name": "filter_situacao",
    "label": "Situacao_Anterior",
    "query": "select distinct situacao_anterior from relacional.tb_cubo_matriculas \nwhere Sexo in ($filter_sexo) and Deficiencia in ($filter_deficiencia) and Transporte in ($filter_transporte)"
   },
   {
    "name": "filter_status",
    "label": "Status_Matricula",
    "query": "select distinct status_matricula from relacional.tb_cubo_matriculas \nwhere Sexo in ($filter_sexo) and Deficiencia in ($filter_deficiencia) and Transporte in ($filter_transporte) and Situacao_Anterior in ($filter_situacao)"
   },
   {
    "name": "filter_turma",
    "label": "Turma",
    "query": "select distinct turma from relacional.tb_cubo_matriculas \nwhere Sexo in ($filter_sexo) and Deficiencia in ($filter_deficiencia) and Transporte in ($filter_transporte) and Situacao_Anterior in ($filter_situacao) and Status_Matricula in ($filter_status)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Alunos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(id_aluno)\r\nFROM\r\n  relacional.tb_cubo_matriculas\r\nWHERE Sexo in ($filter_sexo)\r\nand Deficiencia in ($filter_deficiencia)\r\nand Transporte in ($filter_transporte)\r\nand Situacao_Anterior in ($filter_situacao)\r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma);"
    }
   ]
  },
  {
   "title": "Total Sexo Femenino",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*)\r\nFROM\r\n  relacional.tb_cubo_matriculas\r\nWHERE sexo = 'Feminino'\r\nand Deficiencia in ($filter_deficiencia)\r\nand Transporte in ($filter_transporte)\r\nand Situacao_Anterior in ($filter_situacao)\r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma);"
    }
   ]
  },
  {
   "title": "Total Sexo Masculino",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*)\r\nFROM\r\n  relacional.tb_cubo_matriculas\r\nWHERE sexo = 'Masculino'\r\nand Deficiencia in ($filter_deficiencia)\r\nand Transporte in ($filter_transporte)\r\nand Situacao_Anterior in ($filter_situacao)\r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma);"
    }
   ]
  },
  {
   "title": "Total Veio de Outra Escola",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*)\r\nFROM\r\n  relacional.tb_cubo_matriculas\r\nWHERE veio_outra_escola = 'Sim'\r\nand Sexo in ($filter_sexo)\r\nand Deficiencia in ($filter_deficiencia)\r\nand Transporte in ($filter_transporte)\r\nand Situacao_Anterior in ($filter_situacao)\r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma);"
    }
   ]
  },
  {
   "title": "Total Não Veio de Outra Escola",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*)\r\nFROM\r\n  relacional.tb_cubo_matriculas\r\nWHERE veio_outra_escola = 'Não'\r\nand Sexo in ($filter_sexo)\r\nand Deficiencia in ($filter_deficiencia)\r\nand Transporte in ($filter_transporte)\r\nand Situacao_Anterior in ($filter_situacao)\r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma);"
    }
   ]
  },
  {
   "title": "Tipo Deficiência",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select deficiencia, count(*) as \"Total:\", now() as time from relacional.tb_cubo_matriculas\r\nwhere Sexo in ($filter_sexo)\r\nand Deficiencia in ($filter_deficiencia) \r\nand Transporte in ($filter_transporte) \r\nand Situacao_Anterior in ($filter_situacao) \r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma)\r\ngroup by deficiencia\r\norder by deficiencia"
    }
   ]
  },
  {
   "title": "Tipo Transporte",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select transporte, count(*) as \"Total:\", now() as time from relacional.tb_cubo_matriculas\r\nwhere Sexo in ($filter_sexo)\r\nand Deficiencia in ($filter_deficiencia) \r\nand Transporte in ($filter_transporte) \r\nand Situacao_Anterior in ($filter_situacao) \r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma)\r\ngroup by transporte\r\norder by transporte"
    }
   ]
  },
  {
   "title": "Sexo do Aluno",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sexo,count(*) as qtd, now() as time from relacional.tb_cubo_matriculas\r\nwhere Sexo in ($filter_sexo) \r\nand Deficiencia in ($filter_deficiencia) \r\nand Transporte in ($filter_transporte) \r\nand Situacao_Anterior in ($filter_situacao) \r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma)\r\ngroup by sexo"
    }
   ]
  },
  {
   "title": "Tipo Cor/Raça",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select cor_raca, count(*) as \"Total:\", now() as time from relacional.tb_cubo_matriculas\r\nwhere Sexo in ($filter_sexo)\r\nand Deficiencia in ($filter_deficiencia) \r\nand Transporte in ($filter_transporte) \r\nand Situacao_Anterior in ($filter_situacao) \r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma)\r\ngroup by cor_raca\r\norder by cor_raca"
    }
   ]
  },
  {
   "title": "Situação Anterior",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select situacao_anterior, count(*) as \"Total:\", now() as time from relacional.tb_cubo_matriculas\r\nwhere Sexo in ($filter_sexo)\r\nand Deficiencia in ($filter_deficiencia) \r\nand Transporte in ($filter_transporte) \r\nand Situacao_Anterior in ($filter_situacao) \r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma)\r\ngroup by situacao_anterior\r\norder by situacao_anterior"
    }
   ]
  },
  {
   "title": "Status Matricula",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select status_matricula,count(*) as \"Total\", now() as time from relacional.tb_cubo_matriculas\r\nwhere Sexo in ($filter_sexo) \r\nand Deficiencia in ($filter_deficiencia) \r\nand Transporte in ($filter_transporte) \r\nand Situacao_Anterior in ($filter_situacao) \r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma)\r\ngroup by status_matricula\r\norder by status_matricula"
    }
   ]
  },
  {
   "title": "Tabela Matrícula",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select \r\nmatricula as \"MATRICULA\", nome as \"NOME\", sexo as \"SEXO\", cor_raca as \"COR\", deficiencia as \"DEFICIÊNCIA\", \r\ntransporte as \"TRANSPORTE\", situacao_anterior as \"SITUAÇÃO ANTERIOR\", \r\nstatus_matricula as \"STATUS\"\r\nfrom relacional.tb_cubo_matriculas \r\nwhere Sexo in ($filter_sexo)\r\nand Deficiencia in ($filter_deficiencia) \r\nand Transporte in ($filter_transporte) \r\nand Situacao_Anterior in ($filter_situacao) \r\nand Status_Matricula in ($filter_status)\r\nand Turma in ($filter_turma)\r\norder by nome asc\r\n"
    }
   ]
  }
 ]
}